version: '3.8'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: userservice
      DATABASE_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - spring-security-demo-network
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - spring-security-demo-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: userservice
      DB_PORT: 3306
      DB_HOSTNAME: mysqldb

    networks:
      - spring-security-demo-network
volumes:
  mysql-database-data-volume:

networks:
  spring-security-demo-network: